### ISSUE TITLE
Approved not working well with natbib package

### ISSUE THREAD

**Issue by adrianhelmlingcornell** [publicus/unofficial-uoregon-grad-school-dissertation-latex-markdown-apa-format#18]
Hi all, thanks for your hard work. I am trying to compile the document for the first time in a Gitlab CI/CD environment, I find that I get the following error `! LaTeX Error: Unknown option 'approved' for package 'natbib'.` when I compile.  Here is the yaml file that I am using for the pipeline
```
---
variables:
  LATEX_IMAGE: listx/texlive:2020
build:
  image: $LATEX_IMAGE
  script:
    - latexmk -shell-escape -pdf latex_files/main.tex
    - latexmk -bibtex -pdf -pdflatex="pdflatex -interaction=nonstopmode"
      latex_files/main.tex
    - latexmk -shell-escape -pdf latex_files/main.tex
    - latexmk -shell-escape -pdf latex_files/main.tex
    - latexmk -shell-escape -pdf latex_files/main.tex
  artifacts:
    paths:
      - "*.pdf"
```
I find that I can reach further in the compilation if I comment out the first documentclass line and uncomment the next.
